### ISSUE TITLE
AUR entry + possible plugin inspiration

### ISSUE THREAD

**Issue by mxmilkiib** [sjaehn/BChoppr#1]
Nice work :) I've made an [AUR entry](https://aur.archlinux.org/packages/bchoppr-git). P.S. It's also available in the [Arch binary package user repo](https://github.com/mxmilkb/aur-av-bin/releases) I'm curating.

Also, I saw [this](https://cdm.link/2020/01/sliceshuffler-ableton-live/) the other day and was reminded of your style of plugins.

No continuing issue so I'll close this shortly. P.S. You should stop by and hang out in #lad on Freenode :)

**Comment by sjaehn** [comment]
Thank you, milk. You are the first. You was so quick to build that package. Maybe too quick. The first commit still looks like its antecessor B.Slizr. Programming of some additional features is scheduled. Not only variable step size. And both forward and backward compatibility to the first commit is not guaranteed. Therefore, do not use it for production as an update may destroy your work.

Thank you for the hint to J74 SliceShuffler. Maybe I'll get some additional inspiration.

**Comment by sjaehn** [comment]
SliceShuffler is really an interesting one. I'll keep it in mind for further projects.

**Comment by sjaehn** [comment]
Hi, Milk. Is this something interesting for you: https://github.com/sjaehn/BNoname

It's a very quick draft. I even don't have a name for it.

**Comment by mxmilkiib** [comment]
Wow :) I've built and installed, and I get the interface, which runs with the transport, but I'm not sure how to record sounds. Carla shows level coming in. There's nothing obvious to me in the GUI to record. Is there MIDI control? Or is that yet to come?

**Comment by sjaehn** [comment]
Nothing to record (yet ?). No MIDI. It acts "live" on an incoming audio stream. "Live" means as long as you use the default diagonal line pattern. If you move a pad one step to the right, the corresponding "live slice" will be played one step later. Like a step sequencer-controlled delay.

**Comment by mxmilkiib** [comment]
Ah, I got it, switching up the yellow buttons. Very nice!
