### ISSUE TITLE
Feature request: Pan per chop?

### ISSUE THREAD

**Issue by mahlonsmith** [sjaehn/BChoppr#14]
Just finished a project that I manually set up automation to "bounce" the gated sound between speakers.  Just realized how much easier that would have been if BChoppr had that as a built in feature.

Love the B* utilities!

**Comment by sjaehn** [comment]
Thanks for your idea. Do you you mean different gating for left and right speakers? Or do you think about different panning?

**Comment by mahlonsmith** [comment]
I was thinking specifically of differing panning per step, since that was where I was spending most of my time in drawing automations outside of BChoppr.  I think differing gates per speaker -could- be interesting, but that outcome seems easier to manage in your DAW directly (left and right busses with multiple BChopper instances, for example.)

**Comment by sjaehn** [comment]
Lucky me. And you. I think this is rather easy to realize (compared to different gating). 16 additional control ports in the lv2. Panning in DSP algorithm is easy too. For the GUI, I've got two diffent ways to realize in my mind: (i) Small pan dials just below the step volume sliders. (ii) Tabs, one for volume and one for pan. As you know from some of the other B.Music plugins.

I'd prefer the first way as you can see all at one. If there will be some more effects requested in the future, then I've to think about the second way.

**Comment by mahlonsmith** [comment]
This sounds fantastic.  :+1:

**Comment by sjaehn** [comment]
The current master contains an implementation of step-specific panning (now version 1.11.0). If you want to try ...

There are still some TODOs before the official release. It will be in version 1.12.0.

**Comment by mahlonsmith** [comment]
Holy moly, that was fast.  Just tried it out -- this is exactly what I was after.    Thanks so much, @sjaehn!  This is great.
