### ISSUE TITLE
Git submodules not included in tarball

### ISSUE THREAD

**Issue by dvzrv** [sjaehn/BChoppr#17]
Hi! I package this project for Arch Linux.

Unfortunately I can not package the latest version anymore, as you have switched to using git submodules but do not provide a source tarball that contains these sources.
Tracking git commit checksums is far more work intense than relying on versioned tarballs and their checksums.
Do you plan on adding them?

**Comment by sjaehn** [comment]
I've to admit that this problem was out of my scope. I'll think about it.

**Comment by sjaehn** [comment]
I added a tar.gz to the release. Let me know if this is the one you asked for. Then I can think about an automated way for the future.

**Comment by KottV** [comment]
> I added a tar.gz to the release. Let me know if this is the one you asked for. Then I can think about an automated way for the future.

Hi, this archive is without subfolder, I think it should be `BChoppr-1.12.4` inside.

**Comment by sjaehn** [comment]
Updated, now with base dir.

**Comment by sjaehn** [comment]
... and in the release 1.12.6
