### ISSUE TITLE
Bypass

### ISSUE THREAD

**Issue by pterodattero** [sjaehn/BChoppr#2]
Hey! Could you implement a bypass command in the beautiful plugins you coded? It would be really useful in DAWs to switch them on/off with an automation.

Thx for your work!

**Comment by sjaehn** [comment]
Hi,
thank you for your feedback. Indeed, I should add this feature (and/or a dry/wet dial). I received similar requests for the other B.Music plugins. Although I think it is the DAW's job to provide this feature. May I ask you which DAW do you use?

**Comment by sjaehn** [comment]
Features added to B.Choppr in 8a5c7bb073503ac4f18424dda048d03caf383a4b .

Doing this, I observed and also fixed a weird bug in 6039d6a22788d3561e5e6faaec6e313e67f741d1 .

B.Shapr already has got a dry/wet option (for each shape). Maybe it's worth to think about global bypass & dry/wet in this plugin as well. B.Jumblr has already got a bypass button. B.Slizr will not receive new features and thus no bypassing. And bypassing in B.SEQuenzr would mean something totally different: MIDI bypassing.

**Comment by sjaehn** [comment]
Also B.Shapr just got both bypass an dry/wet features.

**Comment by pterodattero** [comment]
Sorry to answer so late... unfortunately ardour doesn't provide the bypass automation, even if it should in my opinion too. Thank you so much!
