### ISSUE TITLE
Feature request: swing knob

### ISSUE THREAD

**Issue by magnetophon** [sjaehn/BChoppr#4]
Could you make a swing knob, like [x42-stepseq](https://x42-plugins.com/x42/x42-stepseq-8x8)?
When the knob is at 0, the the grid would be regular, and the mode you turn up the swing, the more the even steps get delayed.
The change would be visible in the grid, so you could fine tune it per step.

**Comment by sjaehn** [comment]
Hi Bart,

I got a similar request for B.SEQuenzr (see https://github.com/sjaehn/BSEQuencer/issues/15). There it is a lot more complicated. 

For B.Choppr, I can well imagine to provide some buttons to set the markers (markers are the pentagonal grey knobs which you can horizontally shift to define the slice length) to pre-defined distances. Like:
Button 1: 1/4 - 1/4 - 1/4 - 1/4 - ...
Button 2: 2/4 - 1/4 - 2/4 - 1/4 - ...
.... (any other ideas welcome)

Then you would get a similar functionality as in x42-stepseq. What do you think about ?

**Comment by magnetophon** [comment]
Instead of buttons, I'd prefer a knob or slider.
The cool thing about swing is the in-between values!

**Comment by sjaehn** [comment]
A slider would be fine, too. Let's think about its behavior. 

First, please keep in mind that each marker has two states. Auto and manual. On default all markers are "auto" and their position are calculated by the plugin. Once you dragged a marker it becomes "manual" and its position is fixed unless you drag it again or set it to "auto" by right clicking. 

Thus, there are at least three different possible behaviors for a swing slider:

1) A swing slider will change all marker positions on a "hard" way. All positions are re-calculated and fixed (set to "manual"). The result would be an exact swing pattern as defined by the slider.

2) A swing slider will only change the "auto" markers positions in a soft way. The calculation algorithm for "auto" markers takes the swing value in account. And therefore "auto" markers stay "auto" markers. And "manual" markers keep their positions. The swing pattern will be applied to the auto markers only.

3) Dragging the swing slider will set all markers to "auto" and the calculation algorithm for "auto" markers takes the swing value in account. The result would apparently be the same as in 1). All "manual" settings are gone. And if a marker is dragged afterwards (= set to "manual"), the positions need to be calculated as in 2).

Which kind of behavior would you expect?

**Comment by magnetophon** [comment]
Thanks for considering this!

I would prefer 2.
It would be nice to have a button that sets all sliders to auto, then 3 can be done that way.
Thinking aloud of related stuff: a way to identify which markers are set to manual without right- clicking them all would be nice.  Maybe a color code?

**Comment by sjaehn** [comment]
Manually set markers are now easier to identify. By color - as you suggested. Fixed in 9355005b6096ff287ad68b13cb8744d34fa42cad.

**Comment by sjaehn** [comment]
... and the button to set all markers to auto at once added in 1f000fb6b4a90fb61e087f3a6922d481c0e527ae.

In the next days I will take my hands on the more difficult part ;-)

**Comment by magnetophon** [comment]
Cool, thanks!

**Comment by sjaehn** [comment]
Swing function added in 6a59e6be646a53572c6f585493cbee42969fb145 and 14334c84c38f1e3344e7aa1efe2f95624a55109a. Minor version number needed to be increased as  plugin definition has changed. A new official release will follow after addition some minor stuff and testing.

**Comment by magnetophon** [comment]
Great!

**Comment by sjaehn** [comment]
New version is online. Thank you for the idea. Hope to see it in NixOS. Close issue.

**Comment by magnetophon** [comment]
I updated [my PR](https://github.com/NixOS/nixpkgs/pull/84240).
