### ISSUE TITLE
Swing slider resets when re-opening window 

### ISSUE THREAD

**Issue by magnetophon** [sjaehn/BChoppr#6]
When I change the swing to something other the 1:1, close and re-open the plugin in Ardour, the Swing slider is visually at 1:1, but the sound is as it should be. 

B.Choppr 1.16
Ardour 5.12

**Comment by sjaehn** [comment]
Thank you for reporting. Indeed, swing control was not handled in BChoppr_GUI::portEvent(). Bug fixed in c3b57f0cc88bdca4d7be69867a86bffeb81f1c6d .

**Comment by magnetophon** [comment]
Thanks for the quick fix!  :)
