### ISSUE TITLE
The UI background makes the plug-in hard to read

### ISSUE THREAD

**Issue by unfa** [sjaehn/BChoppr#8]
I've just used B.Choppr for the first time, and it's a really cool plug-in!

The only issue I have with it (and the rest of the B. suite) is that the background image in the UI has a lot of stuff going on and uses the same colors as the interactive UI elements which makes it very hard fort a new user to understand what's going on.

**What my eyes see:**

![image](https://user-images.githubusercontent.com/491704/85234854-ca04a580-b410-11ea-9802-1b392c0d9021.png)

**What my brain sees:**

![image](https://user-images.githubusercontent.com/491704/85234931-5a42ea80-b411-11ea-8e3c-0df119a9e9e5.png)

I'd like to see how it'd look if the background was pure black. It wouldn't be as fancy, but I think it'd make it much much easier for he users to pick this plug-in up and see what's going on.

**Comment by sjaehn** [comment]
Thank you for your remarks. And I agree with your observations. You mentioned something similar about B.Slizr on Youtube some month ago. In response I dimmed the background a bit and I added a black-fading background behind the step sliders.

I've to admit that I was too much influenced by the VST world before I started LV2 programming in early 2018. You find a lot of colorful plugins with faithful reproductions of hardware synth dials and even screws. I think the dial reproductions and the screws are only "snake oil" (White Sea Studio), but I kept the colorful backgrounds. But also the VST world is turning. More and more plugins with a very simple dark mode design come up. So, I should think about to follow the trend (or not).

If you want to know how B.Choppr looks like with a black / white background, please take a look to the just published pre-release of the new B.Schaffl. 

Or if you want to take hands on: Simply edit the surface.png file. This file is encoded by surface.svg. You can find both files in the plugins root directory. The font I use for all plugins is the Good Times free font. I'm open for any new designs as I know that I'm a lousy designer. Let me know.

**Comment by unfa** [comment]
Awesome, thanks!

I could maybe try and come up with some non-intrusive background art for you plug-ins.
