### ISSUE TITLE
Add bypass?

### ISSUE THREAD

**Issue by sonejostudios** [sjaehn/BChoppr#9]
Hi!
First of all, thank you very much for this plugin!
I wrote a similar plugin a couple of years ago, but yours is much better. (https://github.com/sonejostudios/SuperCutSequencer)
I'm missing a bypass-button... or even better a wet/dry knob. would it be possible to add? It is especially useful for automations.

Have a nice day,

Vince

**Comment by sjaehn** [comment]
Hi Vince,

thanks. This feature was already requested before in #2. Thus, bypass and dry/wet mixing are implemented since version 1.4.0.

**Comment by sonejostudios** [comment]
Oh, very nice, thanks!
